[package]
name = "altv_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alt = { path = "../" }
cxx = "1.0"
libloading = "0.6.2"
once_cell = "1.16.0"

[lib]
crate-type = ["cdylib"]
