[package]
name = "alt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resource_main_macro = { path = "../resource_main_macro" }
resource_api = { path = "../resource_api" }
cxx = "1.0"
once_cell = "1.16.0"
specs = "0.18.0"
